### ISSUE TITLE
A few string bugs

### ISSUE THREAD

**Issue by Mental-Reservation** [ck2plus/CK2Plus#219] opened 2021-10-10 16:24 UTC
![bug](https://user-images.githubusercontent.com/51900899/136704615-6ee129ce-6a12-4558-a253-0c21b303a6ac.png)
![bug3](https://user-images.githubusercontent.com/51900899/136704617-e398a454-b891-48b8-b85d-8a4d6d0ee463.png)

**Comment by Whizzer** [comment] 2021-11-02 00:15
Thanks for your reports. The first issue has been fixed in CleanSlate. I couldn't reproduce the second issue, which probably means it's already fixed in the current development version. If you encounter it again after the next update, please provide a savegame.

**Closed as completed** 2022-09-14 19:21 UTC
