### ISSUE TITLE
Games crashes by Click the religion tab button

### ISSUE THREAD

**Issue by Badered10** [ck2plus/CK2Plus#264] opened 2023-09-15 17:12 UTC
Opening the Religion tab as a  ruler Designer causes the game to crash to desktop.

Steps to reproduce:

Start a game as a  Ruler Designer.
Click the religion tab button, or press the F9 hotkey.
Games crashes.

**Comment by schwarherz** [comment] 2023-12-15 17:35
Can't reproduce. Closing issue pending other reports.

**Closed as completed by schwarherz** 2023-12-15 17:35 UTC
