### ISSUE TITLE
Chalcedonian unifition faith events

### ISSUE THREAD

**Issue by Kukuczka4** [ck2plus/CK2Plus#238] opened 2022-01-29 12:42 UTC
Thanks for keeping to develop this mod. I still love CK2 much more than CK3.

I'm playing with 5.0 beta 3 realesed 8 jan as ERE and run into some issuses:

1. After the Antoin a Greek Patriarch Supreme decision was triggered, societes The dominican order and The community of Saint Basil stopped being populated. After succession I can't join any monastic society as ERE male ruler (I mean there are none displayed in societies tab). When I have joined via console The community of Saint Basil some times passed (like 10 years) and new member appeard (a chalcedonian nun with greek rites) and expelled me after 1-2 week when she joined. I see no reason for that (no sins trait, posssesed or sth evil).

2. After the Enforce decision was triggered, Enforce Ephesus decision disappeared, and vice versa. In both situation still as ERE male ruler no monastic society to join. And (idk if intended) no provinces abroad my empire converted to chalcedonian faith (but luckily they are heresies now :)).

**Comment by schwarherz** [comment] 2022-09-14 17:56
Since this is from January, need to check if this is still happening. I suspect it can be closed.

**Comment by Whizzer** [comment] 2023-03-31 16:25
I cannot reproduce (1) and (2) seems to be working as intended.

**Comment by schwarherz** [comment] 2024-03-17 14:20
Closing per above comment.

**Closed as completed by schwarherz** 2024-03-17 14:20 UTC
Labels: bug, Needs Research
